version: "3"

services:
  mongo:
    restart: always
    image: mongo:4.0.8
    container_name: mongo
    # build: 
    #   context: .
    #   dockerfile: mongo-dockerfile
    privileged: true
    ports: 
      - "27017:27017"
    volumes:
      - ./script/mongo/init:/mongo/back
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: movie_srt
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    command: mongod --auth
    networks:
        - movie_vue_net

  mysql_bs:
    image: mysql
    restart: always
    networks:
      - movie_vue_net
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./script/data/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  redis_srt:
    image: redis
    restart: always
    # volumes:
        #   - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - script/redis/init:/etc/redis/conf.d/
    ports: 
      - "6379:6379"
    networks:
      - movie_vue_net


  nginx:
    image: nginx
    restart: always
    volumes:
    #   - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./script/nginx/conf:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - movie_srt
    links:
      - movie_srt

  movie_srt:
    restart: always
    image: movie_srt_vue_flask:1.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - .:/src/notebooks
    #   - /etc/localtime:/etc/localtime  # 时区
    ports:  # 端口映射要用引号
      - "8899:8888"
      - "5002:5000"
      - "5010:5010"
      - "3306:3306"
      - "8080:8080"
      - "8081:8081"
    #   expose: 
    #   - 8000

    links:
      - mysql_bs
      - mongo
      - redis_srt
    networks:
      - movie_vue_net

networks:
  movie_vue_net:
    driver: bridge